### ISSUE TITLE
hide the errors in the appendix code

### ISSUE THREAD

**Issue by juniperlsimonis** [trenchproject/TrenchRmanuscript#4]
for some reason, they are rendering out in the output
perhaps sink the output in a different fashion or perhaps the knitr chunk option is off

**Comment by lbuckley** [comment]
@juniperlsimonis yes, I can't figure out how to hide the errors. Any suggestions for figuring it out? Tried out various knitr chunk options...

**Comment by juniperlsimonis** [comment]
addressing it in my current PR, but it looks like they are coming out of the function as messages, so the knitr chunk option needed was messages=FALSE
